version: '2'
services:
  proxy:
    container_name: proxy-server
    depends_on:
        - intab-webserver
        - intab-apiserver
        - intab-websocketserver
    image: 'nginx:latest'
    links:
        - 'intab-webserver:intab-webserver'
        - 'intab-apiserver:intab-apiserver'
        - 'intab-websocketserver:intab-websocketserver'
    ports:
        - '443:443/tcp'
        - '80:80/tcp'
    restart: always
    volumes:
      - './conf/proxy/nginx.aben.conf:/etc/nginx/nginx.conf:rw'
      - './cert/intab-apiserver:/etc/cert/intab-apiserver:rw'
      - './cert/intab-webserver:/etc/cert/intab-webserver:rw'
  intab-webserver:
    container_name: intab-webserver
    image: 'intab-webserver-dev:latest'
    restart: always
    command: ./run-dev.sh
    volumes:
      - './intab-core:/go/src/intab-core:ro'
      - './intab-webserver:/go/src/intab-webserver:rw'
      - './scripts/run-dev.sh:/go/src/intab-webserver/run-dev.sh:rw'
  intab-apiserver:
    container_name: intab-apiserver
    image: 'intab-apiserver-dev:latest'
    restart: always
    command: ./run-dev.sh
    volumes:
      - './intab-core:/go/src/intab-core:ro'
      - './intab-apiserver:/go/src/intab-apiserver:rw'
      - './scripts/run-dev.sh:/go/src/intab-apiserver/run-dev.sh:rw'
  intab-websocketserver:
    container_name: intab-websocketserver
    image: 'intab-websocketserver-dev:latest'
    restart: always
    command: ./run-dev.sh
    volumes:
      - './intab-core:/go/src/intab-core:ro'
      - './intab-websocketserver:/go/src/intab-websocketserver:rw'
      - './scripts/run-dev.sh:/go/src/intab-websocketserver/run-dev.sh:rw'
  mysql:
    container_name: mysql-server
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: intab
      MYSQL_MAJOR: '5.7'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: intab
    image: 'mariadb:latest'
    ports:
      - '3306:3306/tcp'
    restart: always
    volumes:
      - '/opt/data/intab/data/mysql:/var/lib/mysql:rw'
  redis:
    container_name: redis-server
    image: 'redis:latest'
    ports:
      - '6379:6379/tcp'
    command:
      - '--appendonly'
      - 'yes'
      - '--requirepass'
      - '123456'
    restart: always
    volumes:
      - '/opt/data/intab/data/redis:/data:rw'
