FROM intab-all:latest

WORKDIR /go/src/
COPY intab-core intab-core
COPY intab-webserver intab-webserver

WORKDIR /go/src/intab-webserver
COPY scripts/run-dev.sh run-dev.sh

RUN go-wrapper download

CMD [ "./run-dev.sh" ]
