FROM intab-all:latest

WORKDIR /go/src/
COPY intab-core intab-core
COPY intab-apiserver intab-apiserver

WORKDIR /go/src/intab-apiserver
COPY scripts/run-dev.sh run-dev.sh

RUN go-wrapper download

CMD [ "./run-dev.sh" ]
