FROM golang:alpine3.6

RUN apk add git --no-cache

WORKDIR /go/src/
COPY intab-core intab-core
COPY intab-apiserver intab-apiserver
COPY intab-webserver intab-webserver

WORKDIR /go/src/intab-apiserver
RUN go-wrapper download

WORKDIR /go/src/intab-webserver
RUN go-wrapper download
