FROM golang:alpine3.6

WORKDIR /go/src/
COPY intab-core intab-core
COPY intab-websocketserver intab-websocketserver

WORKDIR /go/src/intab-websocketserver
RUN go-wrapper download
RUN go-wrapper install

CMD [ "go-wrapper", "run" ]
